#!/usr/bin/env python3
"""Enrich and build the PS Vita release dashboard.

Responsibilities:
- Read the release data generated by monitor.py.
- Enrich releases with canonical metadata from PSVitaAlive catalog.json.
- Always include the latest PSVitaAlive Store release itself.
- Keep exactly one visible/stored release per app (the newest one).
- Compare the latest upstream release with PSVitaAlive's catalog version.
- Render GitHub-style Markdown safely.
- Generate a dashboard using PSVitaAlive's official web color palette.
"""

from __future__ import annotations

import html
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import bleach
import mistune
import requests

CATALOG_URL = os.getenv(
    "PSVITAALIVE_CATALOG_URL",
    "https://raw.githubusercontent.com/VegettoSan/PSVitaAlive/main/catalog.json",
)
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "").strip()

HISTORY_FILE = Path("data/releases.json")
SYNC_FILE = Path("data/sync.json")
HTML_FILE = Path("docs/index.html")
HTTP_TIMEOUT = 45
USER_AGENT = "PsVita-Homebrews-New-Releases/3.0"
MAX_PROJECTS = 600

PSVITAALIVE_REPO = "VegettoSan/PSVitaAlive"
PSVITAALIVE_REPO_KEY = "github:vegettosan/psvitaalive"
PSVITAALIVE_ICON = (
    "https://raw.githubusercontent.com/VegettoSan/PSVitaAlive/main/"
    "web/assets/background/PSVitaAlive_Store_logo_psvita.png"
)
PSVITAALIVE_LOGO = (
    "https://raw.githubusercontent.com/VegettoSan/PSVitaAlive/main/"
    "web/assets/logo/PSVitaAlive_Store_logo_text.png"
)
PSVITAALIVE_BACKGROUND = PSVITAALIVE_ICON

MARKDOWN = mistune.create_markdown(
    escape=False,
    plugins=["strikethrough", "table", "task_lists", "url"],
)

ALLOWED_TAGS = set(bleach.sanitizer.ALLOWED_TAGS).union(
    {
        "p", "br", "hr", "div", "span",
        "h1", "h2", "h3", "h4", "h5", "h6",
        "ul", "ol", "li", "pre", "code", "blockquote",
        "table", "thead", "tbody", "tr", "th", "td",
        "img", "del", "input",
    }
)
ALLOWED_ATTRIBUTES: dict[str, list[str]] = {
    "a": ["href", "title", "target", "rel"],
    "img": ["src", "alt", "title", "width", "height", "align"],
    "div": ["align", "class"],
    "span": ["class"],
    "code": ["class"],
    "pre": ["class"],
    "th": ["align"],
    "td": ["align"],
    "input": ["type", "checked", "disabled"],
}
ALLOWED_PROTOCOLS = set(bleach.sanitizer.ALLOWED_PROTOCOLS).union({"data"})


def load_json(path: Path, default: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def save_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def esc(value: Any, *, quote: bool = False) -> str:
    return html.escape(str(value or ""), quote=quote)


def parse_published(value: Any) -> datetime:
    text = str(value or "").strip()
    if not text:
        return datetime.min.replace(tzinfo=timezone.utc)
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return datetime.min.replace(tzinfo=timezone.utc)


def repo_key(platform: str, project: str) -> str:
    return f"{platform}:{project}".lower()


def normalize_repo_url(value: Any) -> tuple[str, str] | None:
    if not isinstance(value, str) or not value.startswith(("http://", "https://")):
        return None

    try:
        parsed = urlparse(value.strip())
    except ValueError:
        return None

    host = parsed.netloc.lower().split(":", 1)[0]
    parts = [part for part in parsed.path.split("/") if part]

    if host in {"github.com", "www.github.com"} and len(parts) >= 2:
        return "github", f"{parts[0]}/{parts[1].removesuffix('.git')}"

    if host in {"gitlab.com", "www.gitlab.com"} and len(parts) >= 2:
        if "-" in parts:
            parts = parts[: parts.index("-")]
        if len(parts) < 2:
            return None
        parts[-1] = parts[-1].removesuffix(".git")
        return "gitlab", "/".join(parts)

    return None


def app_urls(record: dict[str, Any]) -> list[str]:
    urls: list[str] = []

    for key in (
        "source_url", "release_page", "repository", "repository_url",
        "repo_url", "homepage", "website",
    ):
        value = record.get(key)
        if isinstance(value, str):
            urls.append(value)

    links = record.get("links")
    if isinstance(links, list):
        for link in links:
            if isinstance(link, dict) and isinstance(link.get("url"), str):
                urls.append(link["url"])

    return urls


def looks_like_app(record: dict[str, Any]) -> bool:
    name = record.get("name")
    if not isinstance(name, str) or not name.strip():
        return False

    return any(
        key in record
        for key in (
            "id", "title_id", "category_id", "icon", "description",
            "long_description", "version", "source_url", "release_page",
        )
    )


def compact_app(record: dict[str, Any]) -> dict[str, Any]:
    author_ids = record.get("author_ids") if isinstance(record.get("author_ids"), list) else []

    return {
        "id": str(record.get("id") or "").strip(),
        "name": str(record.get("name") or "").strip(),
        "icon": str(record.get("icon") or "").strip(),
        "category": str(record.get("category_id") or "").strip(),
        "description": str(record.get("description") or "").strip(),
        "long_description": str(record.get("long_description") or "").strip(),
        "version": str(record.get("version") or "").strip(),
        "version_date": str(record.get("version_date") or "").strip(),
        "author_ids": [str(item) for item in author_ids if item],
    }


def catalog_repo_index(catalog: Any) -> dict[str, list[dict[str, Any]]]:
    index: dict[str, list[dict[str, Any]]] = {}

    def add_record(record: dict[str, Any]) -> None:
        if not looks_like_app(record):
            return

        app = compact_app(record)
        if not app["name"]:
            return

        seen_repo_keys: set[str] = set()

        for value in app_urls(record):
            normalized = normalize_repo_url(value)
            if not normalized:
                continue

            platform, project = normalized
            key = repo_key(platform, project)

            if key in seen_repo_keys:
                continue
            seen_repo_keys.add(key)

            bucket = index.setdefault(key, [])
            app_identity = (app.get("id"), app.get("name"))
            if not any(
                (existing.get("id"), existing.get("name")) == app_identity
                for existing in bucket
            ):
                bucket.append(app)

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            add_record(node)
            for value in node.values():
                if isinstance(value, (dict, list)):
                    walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(catalog)
    return index


def normalized_text(value: Any) -> str:
    text = html.unescape(str(value or "")).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def choose_primary_app(
    apps: list[dict[str, Any]],
    release: dict[str, Any],
) -> dict[str, Any] | None:
    if not apps:
        return None
    if len(apps) == 1:
        return apps[0]

    haystack = normalized_text(
        " ".join(
            str(release.get(key) or "")
            for key in ("name", "tag", "body", "repo")
        )
    )

    scored: list[tuple[int, int, dict[str, Any]]] = []

    for position, app in enumerate(apps):
        name = normalized_text(app.get("name"))
        app_id = normalized_text(app.get("id"))
        score = 0

        if name and name in haystack:
            score += 20
        if app_id and app_id in haystack:
            score += 12

        for token in name.split():
            if len(token) >= 4 and token in haystack:
                score += 2

        scored.append((score, -position, app))

    scored.sort(key=lambda item: (item[0], item[1]), reverse=True)
    return scored[0][2]


def version_signature(value: Any) -> tuple[tuple[int, ...] | None, str]:
    text = html.unescape(str(value or "")).strip().lower()
    if not text:
        return None, ""

    text = re.sub(r"^\s*(?:version|release)\s*", "", text)
    text = re.sub(r"^\s*v[\s._-]*", "", text)

    numbers = [int(piece) for piece in re.findall(r"\d+", text)]
    if numbers:
        while len(numbers) > 1 and numbers[-1] == 0:
            numbers.pop()
        suffix = re.sub(r"\d+", "", text)
        suffix = re.sub(r"[^a-z]+", "", suffix)
        return tuple(numbers), suffix

    return None, re.sub(r"[^a-z0-9]+", "", text)


def compare_versions(catalog_version: Any, release_version: Any) -> int | None:
    c_numbers, c_suffix = version_signature(catalog_version)
    r_numbers, r_suffix = version_signature(release_version)

    if c_numbers is not None and r_numbers is not None:
        max_len = max(len(c_numbers), len(r_numbers))
        c_pad = c_numbers + (0,) * (max_len - len(c_numbers))
        r_pad = r_numbers + (0,) * (max_len - len(r_numbers))

        if c_pad < r_pad:
            return -1
        if c_pad > r_pad:
            return 1

        if c_suffix and r_suffix and c_suffix != r_suffix:
            return None
        return 0

    _, c_text = version_signature(catalog_version)
    _, r_text = version_signature(release_version)
    if c_text and r_text:
        return 0 if c_text == r_text else None

    return None


def calculate_catalog_status(
    release: dict[str, Any],
    primary: dict[str, Any] | None,
) -> tuple[str, str]:
    latest_version = str(release.get("tag") or release.get("name") or "").strip()

    if repo_key(
        str(release.get("platform") or "github"),
        str(release.get("repo") or ""),
    ) == PSVITAALIVE_REPO_KEY:
        return "uptodate", f"PSVitaAlive oficial · {latest_version or 'última versión'}"

    if not primary:
        return "pending", "No está registrado en PSVitaAlive"

    catalog_version = str(primary.get("version") or "").strip()

    if not catalog_version:
        return "pending", "PSVitaAlive no tiene versión registrada"

    if not latest_version:
        return "pending", f"PSVitaAlive {catalog_version} · release sin versión comparable"

    comparison = compare_versions(catalog_version, latest_version)

    if comparison in (0, 1):
        return "uptodate", f"PSVitaAlive {catalog_version}"

    return "pending", f"PSVitaAlive {catalog_version} → release {latest_version}"


def clear_catalog_metadata(release: dict[str, Any]) -> None:
    for key in (
        "homebrew_name", "homebrew_icon", "homebrew_category",
        "homebrew_description", "homebrew_long_description", "homebrew_id",
        "homebrew_authors", "homebrew_version", "catalog_apps",
    ):
        release.pop(key, None)


def self_app_metadata(release: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": "psvitaalive-store",
        "name": "PSVitaAlive Store",
        "icon": PSVITAALIVE_ICON,
        "category": "utilities",
        "description": "Homebrew store and catalog for PlayStation Vita.",
        "long_description": "PSVitaAlive Store — catálogo y cliente homebrew para PlayStation Vita.",
        "version": str(release.get("tag") or ""),
        "version_date": str(release.get("published") or "")[:10],
        "author_ids": ["vegettosan"],
    }


def enrich_release(release: dict[str, Any], apps: list[dict[str, Any]]) -> None:
    current_repo_key = repo_key(
        str(release.get("platform") or "github"),
        str(release.get("repo") or ""),
    )

    if current_repo_key == PSVITAALIVE_REPO_KEY:
        apps = [self_app_metadata(release)]

    if not apps:
        clear_catalog_metadata(release)
        status, detail = calculate_catalog_status(release, None)
        release["catalog_update_status"] = status
        release["catalog_update_detail"] = detail
        release["catalog_version"] = ""
        return

    primary = choose_primary_app(apps, release) or apps[0]
    ordered = [primary] + [app for app in apps if app is not primary]

    release["homebrew_name"] = primary.get("name") or release.get("name") or release.get("repo")
    release["homebrew_icon"] = primary.get("icon") or ""
    release["homebrew_category"] = primary.get("category") or ""
    release["homebrew_description"] = primary.get("description") or ""
    release["homebrew_long_description"] = primary.get("long_description") or ""
    release["homebrew_id"] = primary.get("id") or ""
    release["homebrew_authors"] = primary.get("author_ids") or []
    release["homebrew_version"] = primary.get("version") or ""
    release["catalog_apps"] = ordered[:12]

    status, detail = calculate_catalog_status(release, primary)
    release["catalog_update_status"] = status
    release["catalog_update_detail"] = detail
    release["catalog_version"] = primary.get("version") or ""


def github_headers() -> dict[str, str]:
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": USER_AGENT,
    }
    if GITHUB_TOKEN:
        headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"
    return headers


def fetch_psvitaalive_latest_release() -> dict[str, Any] | None:
    url = f"https://api.github.com/repos/{PSVITAALIVE_REPO}/releases/latest"

    try:
        response = requests.get(url, headers=github_headers(), timeout=HTTP_TIMEOUT)
        response.raise_for_status()
        item = response.json()
    except (requests.RequestException, ValueError) as exc:
        print(f"⚠️ No se pudo consultar el release de PSVitaAlive: {exc}")
        return None

    assets = []
    for asset in item.get("assets") or []:
        if not isinstance(asset, dict) or not asset.get("browser_download_url"):
            continue
        assets.append(
            {
                "name": asset.get("name") or "archivo",
                "size": asset.get("size", 0) or 0,
                "download_url": asset.get("browser_download_url") or "",
                "content_type": asset.get("content_type") or "",
            }
        )

    return {
        "platform": "github",
        "repo": PSVITAALIVE_REPO,
        "release_id": str(item.get("id") or item.get("tag_name") or ""),
        "tag": item.get("tag_name") or "",
        "name": item.get("name") or item.get("tag_name") or "PSVitaAlive Store",
        "url": item.get("html_url") or f"https://github.com/{PSVITAALIVE_REPO}/releases",
        "published": item.get("published_at") or item.get("created_at") or "",
        "prerelease": bool(item.get("prerelease")),
        "draft": False,
        "body": item.get("body") or "",
        "assets": assets,
        "author": (item.get("author") or {}).get("login") or "VegettoSan",
    }


def exact_release_key(item: dict[str, Any]) -> str:
    platform = str(item.get("platform") or "github").lower()
    repo = str(item.get("repo") or "").strip().lower()
    tag = str(item.get("tag") or "").strip().lower()

    if tag:
        return f"{platform}:{repo}:{tag}"

    release_id = str(item.get("release_id") or "").strip().lower()
    if release_id:
        return f"{platform}:{repo}:{release_id}"

    url = str(item.get("url") or "").strip().lower()
    if url:
        return f"{platform}:{repo}:{url}"

    return f"{platform}:{repo}:{item.get('published') or ''}"


def merge_release_records(
    preferred: dict[str, Any],
    other: dict[str, Any],
) -> dict[str, Any]:
    result = dict(preferred)

    for key, value in other.items():
        current = result.get(key)

        if current in (None, "", [], {}):
            result[key] = value
            continue

        if key == "assets" and isinstance(current, list) and isinstance(value, list):
            known = {
                str(asset.get("download_url") or asset.get("name") or "")
                for asset in current
                if isinstance(asset, dict)
            }
            merged = list(current)
            for asset in value:
                if not isinstance(asset, dict):
                    continue
                identity = str(asset.get("download_url") or asset.get("name") or "")
                if identity and identity not in known:
                    known.add(identity)
                    merged.append(asset)
            result[key] = merged

    return result


def dedupe_exact_history(
    history: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], int]:
    ordered = sorted(
        (item for item in history if isinstance(item, dict)),
        key=lambda item: parse_published(item.get("published")),
        reverse=True,
    )

    unique: dict[str, dict[str, Any]] = {}
    removed = 0

    for item in ordered:
        key = exact_release_key(item)
        if key not in unique:
            unique[key] = item
        else:
            unique[key] = merge_release_records(unique[key], item)
            removed += 1

    return list(unique.values()), removed


def display_identity(item: dict[str, Any]) -> str:
    homebrew_id = normalized_text(item.get("homebrew_id"))
    if homebrew_id:
        return f"app:{homebrew_id}"

    homebrew_name = normalized_text(item.get("homebrew_name"))
    if homebrew_name:
        return f"name:{homebrew_name}"

    return repo_key(
        str(item.get("platform") or "github"),
        str(item.get("repo") or ""),
    )


def release_rank(item: dict[str, Any]) -> tuple[datetime, tuple[int, ...]]:
    published = parse_published(item.get("published"))
    numbers, _ = version_signature(item.get("tag") or item.get("name"))
    return published, numbers or tuple()


def collapse_latest_per_app(
    history: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], int]:
    """Return exactly one release per app, always the newest known release."""
    chosen: dict[str, dict[str, Any]] = {}
    hidden = 0

    for item in history:
        if not isinstance(item, dict):
            continue

        identity = display_identity(item)
        current = chosen.get(identity)

        if current is None:
            chosen[identity] = item
            continue

        hidden += 1
        if release_rank(item) > release_rank(current):
            chosen[identity] = item

    result = sorted(
        chosen.values(),
        key=lambda item: release_rank(item),
        reverse=True,
    )

    # Second visual safety pass: duplicate catalog records can occasionally use
    # different IDs but the same canonical display name. Keep only the newest.
    final: list[dict[str, Any]] = []
    seen_names: set[str] = set()

    for item in result:
        name = normalized_text(item.get("homebrew_name"))
        if name and name in seen_names:
            hidden += 1
            continue
        if name:
            seen_names.add(name)
        final.append(item)

    return final[:MAX_PROJECTS], hidden


def format_size(size: int | float | None) -> str:
    if not size:
        return ""

    value = float(size)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.1f} {unit}"
        value /= 1024

    return ""


def choose_primary_asset(assets: list[dict[str, Any]]) -> dict[str, Any] | None:
    if not assets:
        return None

    for extension in (".vpk", ".skprx", ".suprx", ".self", ".zip"):
        for asset in assets:
            if str(asset.get("name") or "").lower().endswith(extension):
                return asset

    return assets[0]


def render_release_body(raw: Any) -> str:
    text = str(raw or "").strip()

    if not text:
        return "<p>Sin descripción.</p>"

    try:
        rendered = MARKDOWN(text)
    except Exception:
        rendered = f"<pre>{esc(text)}</pre>"

    cleaned = bleach.clean(
        rendered,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        protocols=ALLOWED_PROTOCOLS,
        strip=True,
    )

    cleaned = re.sub(
        r"<a(?![^>]*\btarget=)([^>]*)>",
        r'<a target="_blank" rel="noopener noreferrer"\1>',
        cleaned,
        flags=re.IGNORECASE,
    )

    return cleaned


def generate_dashboard(history: list[dict[str, Any]], sync_info: dict[str, Any]) -> None:
    cards: list[str] = []

    for item in history:
        platform = str(item.get("platform") or "github")
        repo = esc(item.get("repo"))
        release_name = esc(item.get("name") or item.get("tag") or "Release")
        homebrew_name = esc(item.get("homebrew_name") or item.get("name") or item.get("repo") or "Homebrew")
        icon = esc(item.get("homebrew_icon"), quote=True)
        category = esc(item.get("homebrew_category") or "homebrew")
        tag = esc(item.get("tag") or "sin tag")
        release_url = esc(item.get("url") or "#", quote=True)
        published = esc(str(item.get("published") or "")[:16].replace("T", " "))
        catalog_version = esc(item.get("catalog_version") or "")
        catalog_detail = esc(item.get("catalog_update_detail") or "")
        catalog_status = str(item.get("catalog_update_status") or "pending")

        if catalog_status == "uptodate":
            catalog_badge = '<span class="badge catalog-ok">✓ Al día en PSVitaAlive</span>'
        else:
            catalog_badge = '<span class="badge catalog-pending">↻ Pendiente PSVitaAlive</span>'

        prerelease = '<span class="badge pre">PRE-RELEASE</span>' if item.get("prerelease") else ""

        description_raw = str(item.get("body") or item.get("homebrew_description") or "Sin descripción").strip()
        description = render_release_body(description_raw)

        apps = item.get("catalog_apps") if isinstance(item.get("catalog_apps"), list) else []
        extra_apps = [app for app in apps[1:] if isinstance(app, dict) and app.get("name")]
        related = ""

        if extra_apps:
            names = " · ".join(esc(app.get("name")) for app in extra_apps[:5])
            more = len(extra_apps) - 5
            suffix = f" · +{more} más" if more > 0 else ""
            related = f'<div class="related"><span>También asociado:</span> {names}{suffix}</div>'

        if icon:
            icon_html = (
                f'<img class="app-icon" src="{icon}" alt="Icono de {homebrew_name}" '
                'loading="lazy" referrerpolicy="no-referrer" '
                'onerror="this.parentElement.classList.add(\'icon-failed\');this.remove()">'
            )
        else:
            icon_html = ""

        assets = item.get("assets") if isinstance(item.get("assets"), list) else []
        primary_asset = choose_primary_asset(assets)
        buttons: list[str] = []

        if primary_asset:
            url = esc(primary_asset.get("download_url") or "#", quote=True)
            name = esc(primary_asset.get("name") or "Descargar")
            size = format_size(primary_asset.get("size"))
            size_text = f" · {esc(size)}" if size else ""
            buttons.append(
                f'<a class="btn primary" href="{url}" target="_blank" rel="noopener">'
                f'⬇ {name}{size_text}</a>'
            )

        for asset in assets:
            if asset is primary_asset or not isinstance(asset, dict):
                continue
            url = esc(asset.get("download_url") or "#", quote=True)
            name = esc(asset.get("name") or "archivo")
            size = format_size(asset.get("size"))
            size_text = f" · {esc(size)}" if size else ""
            buttons.append(
                f'<a class="btn" href="{url}" target="_blank" rel="noopener">'
                f'{name}{size_text}</a>'
            )

        if not buttons:
            buttons.append('<span class="no-assets">Sin assets publicados</span>')

        search_text = esc(
            " ".join(
                [
                    str(item.get("homebrew_name") or ""),
                    " ".join(str(app.get("name") or "") for app in apps if isinstance(app, dict)),
                    str(item.get("repo") or ""),
                    str(item.get("name") or ""),
                    str(item.get("tag") or ""),
                    str(item.get("homebrew_category") or ""),
                    description_raw,
                ]
            ).lower(),
            quote=True,
        )

        catalog_meta = (
            f'<span class="catalog-version">PSVitaAlive: {catalog_version}</span>'
            if catalog_version
            else '<span class="catalog-version">Sin versión en catálogo</span>'
        )

        cards.append(
            f"""
            <article class="card" data-platform="{platform}" data-catalog="{catalog_status}" data-search="{search_text}">
              <div class="card-layout">
                <div class="icon-wrap">{icon_html}<span class="icon-fallback">PSV</span></div>
                <div class="card-content">
                  <div class="card-top">
                    <div class="title-block">
                      <div class="eyebrow">{category.upper()} · {platform.upper()} · {repo}</div>
                      <h2><a href="{release_url}" target="_blank" rel="noopener">{homebrew_name}</a></h2>
                      <div class="release-name">{release_name}</div>
                    </div>
                    <div class="badges">{catalog_badge}{prerelease}</div>
                  </div>
                  <div class="meta">
                    <span class="tag">{tag}</span>
                    <span>{published or "fecha desconocida"} UTC</span>
                    {catalog_meta}
                  </div>
                  <div class="catalog-detail">{catalog_detail}</div>
                  {related}
                  <div class="body markdown-body">{description}</div>
                  <div class="assets">{''.join(buttons)}</div>
                </div>
              </div>
            </article>
            """
        )

    cards_html = "\n".join(cards) if cards else '<div class="empty">Aún no hay releases registrados.</div>'

    github_count = sum(1 for item in history if item.get("platform") == "github")
    gitlab_count = sum(1 for item in history if item.get("platform") == "gitlab")
    up_to_date = sum(1 for item in history if item.get("catalog_update_status") == "uptodate")
    pending = len(history) - up_to_date
    updated = esc(str(sync_info.get("metadata_enriched_at") or sync_info.get("synced_at") or "")[:16].replace("T", " "))

    document = f"""<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="Últimos releases de homebrew de PS Vita, sincronizados con PSVitaAlive.">
  <title>PS Vita · New Releases</title>
  <style>
    :root {{
      color-scheme: dark;
      --bg:#000000;
      --surface:#373737;
      --surface-hover:#6e6e6e;
      --border:#6e6e6e;
      --text:#aaaaaa;
      --text-secondary:#a0a0a0;
      --text-muted:#6e6e6e;
      --accent:#3bff00;
      --accent-hover:#3bff00;
      --success:#3bff00;
      --warning:#a0a0a0;
      --white:#f5f5f5;
      --radius:12px;
      --container-width:1200px;
    }}
    * {{ box-sizing:border-box; }}
    html {{ scroll-behavior:smooth; }}
    body {{
      margin:0;
      min-height:100vh;
      background:var(--bg);
      color:var(--text);
      font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
      line-height:1.5;
      position:relative;
      overflow-x:hidden;
    }}
    body::before {{
      content:"";
      position:fixed;
      inset:0;
      z-index:-2;
      background-image:url("{PSVITAALIVE_BACKGROUND}");
      background-repeat:no-repeat;
      background-position:center;
      background-size:min(900px,80vw);
      opacity:.18;
      filter:blur(2px);
      pointer-events:none;
    }}
    body::after {{
      content:"";
      position:fixed;
      inset:0;
      z-index:-1;
      background:rgba(0,0,0,.58);
      pointer-events:none;
    }}
    a {{ color:inherit; text-decoration:none; }}
    .wrap {{ width:min(calc(100% - 40px),var(--container-width)); margin-inline:auto; }}
    header {{ padding:38px 0 22px; }}
    .hero {{
      border:1px solid var(--border);
      background:rgba(55,55,55,.80);
      border-radius:var(--radius);
      padding:24px;
      box-shadow:0 18px 50px rgba(0,0,0,.28);
      backdrop-filter:blur(12px);
    }}
    .brand-row {{ display:flex; align-items:center; gap:20px; }}
    .brand-logo {{ width:min(360px,65vw); max-height:82px; object-fit:contain; object-position:left center; }}
    .kicker {{ color:var(--accent); font-weight:800; letter-spacing:.12em; font-size:.74rem; text-transform:uppercase; }}
    h1 {{ color:var(--white); margin:4px 0 6px; font-size:clamp(1.8rem,4vw,3.1rem); line-height:1.02; }}
    .lead {{ margin:0; color:var(--text-secondary); max-width:820px; }}
    .stats {{ display:grid; grid-template-columns:repeat(5,1fr); gap:10px; margin-top:20px; }}
    .stat {{ border:1px solid var(--border); background:rgba(0,0,0,.34); border-radius:var(--radius); padding:12px 14px; }}
    .stat strong {{ display:block; color:var(--white); font-size:1.22rem; }}
    .stat strong.green {{ color:var(--accent); }}
    .stat span {{ color:var(--text-secondary); font-size:.77rem; }}
    .toolbar {{
      position:sticky;
      top:0;
      z-index:20;
      display:flex;
      gap:10px;
      flex-wrap:wrap;
      padding:12px 0;
      background:rgba(0,0,0,.88);
      backdrop-filter:blur(14px);
    }}
    input,select {{
      min-height:44px;
      border:1px solid var(--border);
      border-radius:var(--radius);
      background:#171717;
      color:var(--white);
      padding:0 13px;
      outline:none;
    }}
    input {{ flex:1 1 330px; }}
    input:focus,select:focus {{ border-color:var(--accent); box-shadow:0 0 0 2px rgba(59,255,0,.18); }}
    #count {{ margin-left:auto; align-self:center; color:var(--text-secondary); font-size:.84rem; }}
    main {{ padding:2px 0 64px; }}
    .card {{
      border:1px solid var(--border);
      border-left:4px solid var(--accent);
      background:rgba(55,55,55,.84);
      border-radius:var(--radius);
      padding:18px;
      margin:12px 0;
      box-shadow:0 12px 34px rgba(0,0,0,.22);
      backdrop-filter:blur(8px);
      transition:.16s ease;
    }}
    .card:hover {{ background:rgba(62,62,62,.92); border-color:#8b8b8b; }}
    .card-layout {{ display:grid; grid-template-columns:92px minmax(0,1fr); gap:17px; }}
    .icon-wrap {{
      width:92px;
      height:92px;
      border:1px solid var(--border);
      border-radius:var(--radius);
      background:#000;
      overflow:hidden;
      display:grid;
      place-items:center;
      position:relative;
    }}
    .app-icon {{ width:100%; height:100%; object-fit:cover; position:relative; z-index:2; }}
    .icon-fallback {{ position:absolute; color:var(--accent); font-weight:900; letter-spacing:.08em; }}
    .card-top {{ display:flex; justify-content:space-between; gap:16px; align-items:flex-start; }}
    .title-block {{ min-width:0; }}
    .eyebrow {{ color:var(--text-secondary); font-size:.72rem; font-weight:750; letter-spacing:.045em; overflow-wrap:anywhere; }}
    h2 {{ margin:4px 0 0; color:var(--white); font-size:1.42rem; }}
    h2 a:hover {{ color:var(--accent); }}
    .release-name {{ color:var(--accent); font-size:.86rem; margin-top:2px; }}
    .badges {{ display:flex; gap:6px; flex-wrap:wrap; justify-content:flex-end; }}
    .badge {{ white-space:nowrap; padding:5px 9px; border-radius:999px; font-size:.66rem; font-weight:900; letter-spacing:.035em; border:1px solid var(--border); }}
    .catalog-ok {{ color:#000; background:var(--accent); border-color:var(--accent); }}
    .catalog-pending {{ color:var(--white); background:#1b1b1b; border-color:var(--warning); }}
    .pre {{ color:#000; background:var(--warning); border-color:var(--warning); }}
    .meta {{ display:flex; gap:9px; flex-wrap:wrap; align-items:center; margin:10px 0 4px; color:var(--text-secondary); font-size:.79rem; }}
    .tag {{ color:#000; background:var(--accent); border:1px solid var(--accent); padding:2px 7px; border-radius:7px; font-weight:800; }}
    .catalog-version {{ color:var(--white); }}
    .catalog-detail {{ color:var(--text-secondary); font-size:.76rem; margin-bottom:8px; }}
    .related {{ color:var(--text-secondary); font-size:.76rem; margin:5px 0 8px; }}
    .related span {{ color:var(--accent); font-weight:700; }}
    .body {{ color:#d0d0d0; font-size:.91rem; line-height:1.55; max-height:300px; overflow:auto; padding:4px 8px 4px 0; overflow-wrap:anywhere; }}
    .markdown-body h1,.markdown-body h2,.markdown-body h3,.markdown-body h4,.markdown-body h5,.markdown-body h6 {{ color:var(--white); margin:1em 0 .45em; line-height:1.25; }}
    .markdown-body h1 {{ font-size:1.35rem; }} .markdown-body h2 {{ font-size:1.18rem; }} .markdown-body h3 {{ font-size:1.04rem; }}
    .markdown-body p {{ margin:.55em 0; }}
    .markdown-body ul,.markdown-body ol {{ padding-left:1.45rem; margin:.55em 0; }}
    .markdown-body a {{ color:var(--accent); text-decoration:underline; text-underline-offset:2px; }}
    .markdown-body blockquote {{ border-left:3px solid var(--accent); margin:.8em 0; padding:.15em 0 .15em .9em; color:var(--text-secondary); }}
    .markdown-body code {{ background:#111; color:var(--accent); border:1px solid #4c4c4c; padding:.12em .35em; border-radius:5px; }}
    .markdown-body pre {{ background:#111; border:1px solid var(--border); padding:12px; border-radius:var(--radius); overflow:auto; }}
    .markdown-body pre code {{ border:0; padding:0; background:transparent; color:#d8d8d8; }}
    .markdown-body img {{ max-width:100%; height:auto; border-radius:var(--radius); display:block; margin:10px auto; }}
    .markdown-body table {{ width:100%; border-collapse:collapse; margin:.8em 0; }}
    .markdown-body th,.markdown-body td {{ border:1px solid var(--border); padding:6px 8px; text-align:left; }}
    .markdown-body th {{ color:var(--white); background:#242424; }}
    .markdown-body hr {{ border:0; border-top:1px solid var(--border); margin:1em 0; }}
    .assets {{ display:flex; gap:8px; flex-wrap:wrap; margin-top:14px; }}
    .btn {{ text-decoration:none; border:1px solid var(--border); background:#1c1c1c; color:var(--white); padding:8px 11px; border-radius:var(--radius); font-size:.78rem; transition:.15s ease; }}
    .btn:hover {{ border-color:var(--accent); color:var(--accent); transform:translateY(-1px); }}
    .btn.primary {{ border-color:var(--accent); background:rgba(59,255,0,.12); color:var(--accent); font-weight:800; }}
    .no-assets,.empty {{ color:var(--text-secondary); }}
    footer {{ color:var(--text-secondary); text-align:center; padding:0 0 38px; font-size:.8rem; }}
    @media (max-width:900px) {{ .stats {{ grid-template-columns:repeat(2,1fr); }} #count {{ width:100%; margin-left:0; }} }}
    @media (max-width:620px) {{
      .wrap {{ width:min(calc(100% - 20px),var(--container-width)); }}
      header {{ padding-top:20px; }}
      .hero {{ padding:18px; }}
      .brand-row {{ display:block; }}
      .brand-logo {{ margin-bottom:10px; }}
      .stats {{ grid-template-columns:1fr 1fr; }}
      .card {{ padding:14px; }}
      .card-layout {{ grid-template-columns:64px minmax(0,1fr); gap:11px; }}
      .icon-wrap {{ width:64px; height:64px; }}
      .card-top {{ flex-direction:column; }}
      .badges {{ justify-content:flex-start; }}
      h2 {{ font-size:1.16rem; }}
    }}
  </style>
</head>
<body>
  <header class="wrap">
    <section class="hero">
      <div class="brand-row">
        <img class="brand-logo" src="{PSVITAALIVE_LOGO}" alt="PSVitaAlive Store">
        <div>
          <div class="kicker">Release Tracker</div>
          <h1>PS Vita New Releases</h1>
          <p class="lead">Una sola tarjeta por app, siempre con su release más reciente y comparada contra la versión disponible en PSVitaAlive.</p>
        </div>
      </div>
      <div class="stats">
        <div class="stat"><strong>{len(history)}</strong><span>apps con release</span></div>
        <div class="stat"><strong class="green">{up_to_date}</strong><span>al día en PSVitaAlive</span></div>
        <div class="stat"><strong>{pending}</strong><span>pendientes</span></div>
        <div class="stat"><strong>{github_count}</strong><span>GitHub</span></div>
        <div class="stat"><strong>{gitlab_count}</strong><span>GitLab</span></div>
      </div>
    </section>
  </header>

  <div class="wrap toolbar">
    <input id="search" type="search" placeholder="Buscar app, repositorio, versión o categoría…" autocomplete="off">
    <select id="platform">
      <option value="all">GitHub + GitLab</option>
      <option value="github">GitHub</option>
      <option value="gitlab">GitLab</option>
    </select>
    <select id="catalog-status">
      <option value="all">Todo PSVitaAlive</option>
      <option value="uptodate">✓ Al día en PSVitaAlive</option>
      <option value="pending">↻ Pendientes por actualizar</option>
    </select>
    <span id="count"></span>
  </div>

  <main class="wrap" id="releases">{cards_html}</main>

  <footer class="wrap">
    Actualizado: {updated or 'N/A'} UTC · Metadatos y paleta visual: PSVitaAlive
  </footer>

  <script>
    const search=document.getElementById('search');
    const platform=document.getElementById('platform');
    const catalogStatus=document.getElementById('catalog-status');
    const cards=[...document.querySelectorAll('.card')];
    const count=document.getElementById('count');

    function filterCards(){{
      const q=search.value.trim().toLowerCase();
      const p=platform.value;
      const s=catalogStatus.value;
      let visible=0;

      for(const card of cards){{
        const textOk=!q||card.dataset.search.includes(q);
        const platformOk=p==='all'||card.dataset.platform===p;
        const statusOk=s==='all'||card.dataset.catalog===s;
        const show=textOk&&platformOk&&statusOk;
        card.hidden=!show;
        if(show)visible++;
      }}

      count.textContent=`${{visible}} de ${{cards.length}} apps`;
    }}

    search.addEventListener('input',filterCards);
    platform.addEventListener('change',filterCards);
    catalogStatus.addEventListener('change',filterCards);
    filterCards();
  </script>
</body>
</html>
"""

    HTML_FILE.parent.mkdir(parents=True, exist_ok=True)
    HTML_FILE.write_text(document, encoding="utf-8")


def main() -> int:
    history = load_json(HISTORY_FILE, [])
    sync_info = load_json(SYNC_FILE, {})

    if not isinstance(history, list):
        history = []
    if not isinstance(sync_info, dict):
        sync_info = {}

    response = requests.get(
        CATALOG_URL,
        timeout=HTTP_TIMEOUT,
        headers={"User-Agent": USER_AGENT},
    )
    response.raise_for_status()
    catalog = response.json()
    index = catalog_repo_index(catalog)

    # PSVitaAlive itself is the catalog/store project, so it may not appear as a
    # normal catalog entry. Pull its latest release explicitly so a new Store
    # release is visible immediately whenever the dashboard rebuilds.
    self_release = fetch_psvitaalive_latest_release()
    if self_release:
        history.append(self_release)

    history, exact_removed = dedupe_exact_history(history)

    matched = 0
    with_icon = 0

    for release in history:
        if not isinstance(release, dict):
            continue

        key = repo_key(
            str(release.get("platform") or "github"),
            str(release.get("repo") or ""),
        )
        apps = index.get(key, [])

        if apps or key == PSVITAALIVE_REPO_KEY:
            matched += 1

        enrich_release(release, apps)

        if release.get("homebrew_icon"):
            with_icon += 1

    history, older_hidden = collapse_latest_per_app(history)

    # From this point releases.json is intentionally a current-state data set,
    # not an archive: exactly one newest release per app.
    save_json(HISTORY_FILE, history)

    up_to_date = sum(
        1 for item in history
        if item.get("catalog_update_status") == "uptodate"
    )
    pending = len(history) - up_to_date

    sync_info["catalog_metadata_matches"] = matched
    sync_info["catalog_icons"] = with_icon
    sync_info["metadata_enriched_at"] = datetime.now(timezone.utc).isoformat()
    sync_info["exact_duplicates_removed"] = exact_removed
    sync_info["older_app_releases_removed"] = older_hidden
    sync_info["catalog_up_to_date"] = up_to_date
    sync_info["catalog_pending"] = pending
    sync_info["dashboard_apps"] = len(history)
    sync_info["psvitaalive_self_release"] = str(self_release.get("tag") or "") if self_release else ""

    save_json(SYNC_FILE, sync_info)
    generate_dashboard(history, sync_info)

    print(
        f"🎨 Dashboard: {len(history)} apps únicas; "
        f"{up_to_date} al día; {pending} pendientes; "
        f"{exact_removed} duplicados exactos eliminados; "
        f"{older_hidden} releases antiguos/repetidos eliminados; "
        f"PSVitaAlive={sync_info.get('psvitaalive_self_release') or 'N/A'}."
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
